
from __future__ import unicode_literals
from __future__ import print_function
from __future__ import division
from __future__ import absolute_import

from builtins import super
from future import standard_library
standard_library.install_aliases()

from . import unicorn
from . import unicorn_const
from . import mips_const


class Base(unicorn.Uc):
    def __init__(self, mode=None):
        super().__init__(unicorn_const.UC_ARCH_MIPS, mode)
        self.reg = Reg_mips(self)


class mipsel_32(Base):
    def __init__(self):
        super().__init__(unicorn_const.UC_MODE_LITTLE_ENDIAN|unicorn_const.UC_MODE_32)


class mipsel_64(Base):
    def __init__(self):
        super().__init__(unicorn_const.UC_MODE_LITTLE_ENDIAN|unicorn_const.UC_MODE_64)


class mipseb_32(Base):
    def __init__(self):
        super().__init__(unicorn_const.UC_MODE_BIG_ENDIAN|unicorn_const.UC_MODE_32)


class mipseb_64(Base):
    def __init__(self):
        super().__init__(unicorn_const.UC_MODE_BIG_ENDIAN|unicorn_const.UC_MODE_64)

class Reg_mips(unicorn.Registers):

    _0 = unicorn.Register(mips_const.UC_MIPS_REG_0)
    _1 = unicorn.Register(mips_const.UC_MIPS_REG_1)
    _10 = unicorn.Register(mips_const.UC_MIPS_REG_10)
    _11 = unicorn.Register(mips_const.UC_MIPS_REG_11)
    _12 = unicorn.Register(mips_const.UC_MIPS_REG_12)
    _13 = unicorn.Register(mips_const.UC_MIPS_REG_13)
    _14 = unicorn.Register(mips_const.UC_MIPS_REG_14)
    _15 = unicorn.Register(mips_const.UC_MIPS_REG_15)
    _16 = unicorn.Register(mips_const.UC_MIPS_REG_16)
    _17 = unicorn.Register(mips_const.UC_MIPS_REG_17)
    _18 = unicorn.Register(mips_const.UC_MIPS_REG_18)
    _19 = unicorn.Register(mips_const.UC_MIPS_REG_19)
    _2 = unicorn.Register(mips_const.UC_MIPS_REG_2)
    _20 = unicorn.Register(mips_const.UC_MIPS_REG_20)
    _21 = unicorn.Register(mips_const.UC_MIPS_REG_21)
    _22 = unicorn.Register(mips_const.UC_MIPS_REG_22)
    _23 = unicorn.Register(mips_const.UC_MIPS_REG_23)
    _24 = unicorn.Register(mips_const.UC_MIPS_REG_24)
    _25 = unicorn.Register(mips_const.UC_MIPS_REG_25)
    _26 = unicorn.Register(mips_const.UC_MIPS_REG_26)
    _27 = unicorn.Register(mips_const.UC_MIPS_REG_27)
    _28 = unicorn.Register(mips_const.UC_MIPS_REG_28)
    _29 = unicorn.Register(mips_const.UC_MIPS_REG_29)
    _3 = unicorn.Register(mips_const.UC_MIPS_REG_3)
    _30 = unicorn.Register(mips_const.UC_MIPS_REG_30)
    _31 = unicorn.Register(mips_const.UC_MIPS_REG_31)
    _4 = unicorn.Register(mips_const.UC_MIPS_REG_4)
    _5 = unicorn.Register(mips_const.UC_MIPS_REG_5)
    _6 = unicorn.Register(mips_const.UC_MIPS_REG_6)
    _7 = unicorn.Register(mips_const.UC_MIPS_REG_7)
    _8 = unicorn.Register(mips_const.UC_MIPS_REG_8)
    _9 = unicorn.Register(mips_const.UC_MIPS_REG_9)
    a0 = unicorn.Register(mips_const.UC_MIPS_REG_A0)
    a1 = unicorn.Register(mips_const.UC_MIPS_REG_A1)
    a2 = unicorn.Register(mips_const.UC_MIPS_REG_A2)
    a3 = unicorn.Register(mips_const.UC_MIPS_REG_A3)
    ac0 = unicorn.Register(mips_const.UC_MIPS_REG_AC0)
    ac1 = unicorn.Register(mips_const.UC_MIPS_REG_AC1)
    ac2 = unicorn.Register(mips_const.UC_MIPS_REG_AC2)
    ac3 = unicorn.Register(mips_const.UC_MIPS_REG_AC3)
    at = unicorn.Register(mips_const.UC_MIPS_REG_AT)
    cc0 = unicorn.Register(mips_const.UC_MIPS_REG_CC0)
    cc1 = unicorn.Register(mips_const.UC_MIPS_REG_CC1)
    cc2 = unicorn.Register(mips_const.UC_MIPS_REG_CC2)
    cc3 = unicorn.Register(mips_const.UC_MIPS_REG_CC3)
    cc4 = unicorn.Register(mips_const.UC_MIPS_REG_CC4)
    cc5 = unicorn.Register(mips_const.UC_MIPS_REG_CC5)
    cc6 = unicorn.Register(mips_const.UC_MIPS_REG_CC6)
    cc7 = unicorn.Register(mips_const.UC_MIPS_REG_CC7)
    dspcarry = unicorn.Register(mips_const.UC_MIPS_REG_DSPCARRY)
    dspccond = unicorn.Register(mips_const.UC_MIPS_REG_DSPCCOND)
    dspefi = unicorn.Register(mips_const.UC_MIPS_REG_DSPEFI)
    dspoutflag = unicorn.Register(mips_const.UC_MIPS_REG_DSPOUTFLAG)
    dspoutflag16_19 = unicorn.Register(mips_const.UC_MIPS_REG_DSPOUTFLAG16_19)
    dspoutflag20 = unicorn.Register(mips_const.UC_MIPS_REG_DSPOUTFLAG20)
    dspoutflag21 = unicorn.Register(mips_const.UC_MIPS_REG_DSPOUTFLAG21)
    dspoutflag22 = unicorn.Register(mips_const.UC_MIPS_REG_DSPOUTFLAG22)
    dspoutflag23 = unicorn.Register(mips_const.UC_MIPS_REG_DSPOUTFLAG23)
    dsppos = unicorn.Register(mips_const.UC_MIPS_REG_DSPPOS)
    dspscount = unicorn.Register(mips_const.UC_MIPS_REG_DSPSCOUNT)
    ending = unicorn.Register(mips_const.UC_MIPS_REG_ENDING)
    f0 = unicorn.Register(mips_const.UC_MIPS_REG_F0)
    f1 = unicorn.Register(mips_const.UC_MIPS_REG_F1)
    f10 = unicorn.Register(mips_const.UC_MIPS_REG_F10)
    f11 = unicorn.Register(mips_const.UC_MIPS_REG_F11)
    f12 = unicorn.Register(mips_const.UC_MIPS_REG_F12)
    f13 = unicorn.Register(mips_const.UC_MIPS_REG_F13)
    f14 = unicorn.Register(mips_const.UC_MIPS_REG_F14)
    f15 = unicorn.Register(mips_const.UC_MIPS_REG_F15)
    f16 = unicorn.Register(mips_const.UC_MIPS_REG_F16)
    f17 = unicorn.Register(mips_const.UC_MIPS_REG_F17)
    f18 = unicorn.Register(mips_const.UC_MIPS_REG_F18)
    f19 = unicorn.Register(mips_const.UC_MIPS_REG_F19)
    f2 = unicorn.Register(mips_const.UC_MIPS_REG_F2)
    f20 = unicorn.Register(mips_const.UC_MIPS_REG_F20)
    f21 = unicorn.Register(mips_const.UC_MIPS_REG_F21)
    f22 = unicorn.Register(mips_const.UC_MIPS_REG_F22)
    f23 = unicorn.Register(mips_const.UC_MIPS_REG_F23)
    f24 = unicorn.Register(mips_const.UC_MIPS_REG_F24)
    f25 = unicorn.Register(mips_const.UC_MIPS_REG_F25)
    f26 = unicorn.Register(mips_const.UC_MIPS_REG_F26)
    f27 = unicorn.Register(mips_const.UC_MIPS_REG_F27)
    f28 = unicorn.Register(mips_const.UC_MIPS_REG_F28)
    f29 = unicorn.Register(mips_const.UC_MIPS_REG_F29)
    f3 = unicorn.Register(mips_const.UC_MIPS_REG_F3)
    f30 = unicorn.Register(mips_const.UC_MIPS_REG_F30)
    f31 = unicorn.Register(mips_const.UC_MIPS_REG_F31)
    f4 = unicorn.Register(mips_const.UC_MIPS_REG_F4)
    f5 = unicorn.Register(mips_const.UC_MIPS_REG_F5)
    f6 = unicorn.Register(mips_const.UC_MIPS_REG_F6)
    f7 = unicorn.Register(mips_const.UC_MIPS_REG_F7)
    f8 = unicorn.Register(mips_const.UC_MIPS_REG_F8)
    f9 = unicorn.Register(mips_const.UC_MIPS_REG_F9)
    fcc0 = unicorn.Register(mips_const.UC_MIPS_REG_FCC0)
    fcc1 = unicorn.Register(mips_const.UC_MIPS_REG_FCC1)
    fcc2 = unicorn.Register(mips_const.UC_MIPS_REG_FCC2)
    fcc3 = unicorn.Register(mips_const.UC_MIPS_REG_FCC3)
    fcc4 = unicorn.Register(mips_const.UC_MIPS_REG_FCC4)
    fcc5 = unicorn.Register(mips_const.UC_MIPS_REG_FCC5)
    fcc6 = unicorn.Register(mips_const.UC_MIPS_REG_FCC6)
    fcc7 = unicorn.Register(mips_const.UC_MIPS_REG_FCC7)
    fp = unicorn.Register(mips_const.UC_MIPS_REG_FP)
    gp = unicorn.Register(mips_const.UC_MIPS_REG_GP)
    hi = unicorn.Register(mips_const.UC_MIPS_REG_HI)
    hi0 = unicorn.Register(mips_const.UC_MIPS_REG_HI0)
    hi1 = unicorn.Register(mips_const.UC_MIPS_REG_HI1)
    hi2 = unicorn.Register(mips_const.UC_MIPS_REG_HI2)
    hi3 = unicorn.Register(mips_const.UC_MIPS_REG_HI3)
    invalid = unicorn.Register(mips_const.UC_MIPS_REG_INVALID)
    k0 = unicorn.Register(mips_const.UC_MIPS_REG_K0)
    k1 = unicorn.Register(mips_const.UC_MIPS_REG_K1)
    lo = unicorn.Register(mips_const.UC_MIPS_REG_LO)
    lo0 = unicorn.Register(mips_const.UC_MIPS_REG_LO0)
    lo1 = unicorn.Register(mips_const.UC_MIPS_REG_LO1)
    lo2 = unicorn.Register(mips_const.UC_MIPS_REG_LO2)
    lo3 = unicorn.Register(mips_const.UC_MIPS_REG_LO3)
    mpl0 = unicorn.Register(mips_const.UC_MIPS_REG_MPL0)
    mpl1 = unicorn.Register(mips_const.UC_MIPS_REG_MPL1)
    mpl2 = unicorn.Register(mips_const.UC_MIPS_REG_MPL2)
    p0 = unicorn.Register(mips_const.UC_MIPS_REG_P0)
    p1 = unicorn.Register(mips_const.UC_MIPS_REG_P1)
    p2 = unicorn.Register(mips_const.UC_MIPS_REG_P2)
    pc = unicorn.Register(mips_const.UC_MIPS_REG_PC)
    ra = unicorn.Register(mips_const.UC_MIPS_REG_RA)
    s0 = unicorn.Register(mips_const.UC_MIPS_REG_S0)
    s1 = unicorn.Register(mips_const.UC_MIPS_REG_S1)
    s2 = unicorn.Register(mips_const.UC_MIPS_REG_S2)
    s3 = unicorn.Register(mips_const.UC_MIPS_REG_S3)
    s4 = unicorn.Register(mips_const.UC_MIPS_REG_S4)
    s5 = unicorn.Register(mips_const.UC_MIPS_REG_S5)
    s6 = unicorn.Register(mips_const.UC_MIPS_REG_S6)
    s7 = unicorn.Register(mips_const.UC_MIPS_REG_S7)
    s8 = unicorn.Register(mips_const.UC_MIPS_REG_S8)
    sp = unicorn.Register(mips_const.UC_MIPS_REG_SP)
    t0 = unicorn.Register(mips_const.UC_MIPS_REG_T0)
    t1 = unicorn.Register(mips_const.UC_MIPS_REG_T1)
    t2 = unicorn.Register(mips_const.UC_MIPS_REG_T2)
    t3 = unicorn.Register(mips_const.UC_MIPS_REG_T3)
    t4 = unicorn.Register(mips_const.UC_MIPS_REG_T4)
    t5 = unicorn.Register(mips_const.UC_MIPS_REG_T5)
    t6 = unicorn.Register(mips_const.UC_MIPS_REG_T6)
    t7 = unicorn.Register(mips_const.UC_MIPS_REG_T7)
    t8 = unicorn.Register(mips_const.UC_MIPS_REG_T8)
    t9 = unicorn.Register(mips_const.UC_MIPS_REG_T9)
    v0 = unicorn.Register(mips_const.UC_MIPS_REG_V0)
    v1 = unicorn.Register(mips_const.UC_MIPS_REG_V1)
    w0 = unicorn.Register(mips_const.UC_MIPS_REG_W0)
    w1 = unicorn.Register(mips_const.UC_MIPS_REG_W1)
    w10 = unicorn.Register(mips_const.UC_MIPS_REG_W10)
    w11 = unicorn.Register(mips_const.UC_MIPS_REG_W11)
    w12 = unicorn.Register(mips_const.UC_MIPS_REG_W12)
    w13 = unicorn.Register(mips_const.UC_MIPS_REG_W13)
    w14 = unicorn.Register(mips_const.UC_MIPS_REG_W14)
    w15 = unicorn.Register(mips_const.UC_MIPS_REG_W15)
    w16 = unicorn.Register(mips_const.UC_MIPS_REG_W16)
    w17 = unicorn.Register(mips_const.UC_MIPS_REG_W17)
    w18 = unicorn.Register(mips_const.UC_MIPS_REG_W18)
    w19 = unicorn.Register(mips_const.UC_MIPS_REG_W19)
    w2 = unicorn.Register(mips_const.UC_MIPS_REG_W2)
    w20 = unicorn.Register(mips_const.UC_MIPS_REG_W20)
    w21 = unicorn.Register(mips_const.UC_MIPS_REG_W21)
    w22 = unicorn.Register(mips_const.UC_MIPS_REG_W22)
    w23 = unicorn.Register(mips_const.UC_MIPS_REG_W23)
    w24 = unicorn.Register(mips_const.UC_MIPS_REG_W24)
    w25 = unicorn.Register(mips_const.UC_MIPS_REG_W25)
    w26 = unicorn.Register(mips_const.UC_MIPS_REG_W26)
    w27 = unicorn.Register(mips_const.UC_MIPS_REG_W27)
    w28 = unicorn.Register(mips_const.UC_MIPS_REG_W28)
    w29 = unicorn.Register(mips_const.UC_MIPS_REG_W29)
    w3 = unicorn.Register(mips_const.UC_MIPS_REG_W3)
    w30 = unicorn.Register(mips_const.UC_MIPS_REG_W30)
    w31 = unicorn.Register(mips_const.UC_MIPS_REG_W31)
    w4 = unicorn.Register(mips_const.UC_MIPS_REG_W4)
    w5 = unicorn.Register(mips_const.UC_MIPS_REG_W5)
    w6 = unicorn.Register(mips_const.UC_MIPS_REG_W6)
    w7 = unicorn.Register(mips_const.UC_MIPS_REG_W7)
    w8 = unicorn.Register(mips_const.UC_MIPS_REG_W8)
    w9 = unicorn.Register(mips_const.UC_MIPS_REG_W9)
    zero = unicorn.Register(mips_const.UC_MIPS_REG_ZERO)

    def __init__(self, mu):
        self.mu = mu